version: '3.4'

services:
  docker.api:
    image: "${DOCKER_USERNAME}Jadra.Api:latest"
    build:
      context: .
      dockerfile: ProjectManagement.API/Dockerfile
    depends_on:
      - redis
    networks:
      - normandy

  projectmanagement.worker:
    image: "${DOCKER_USERNAME}Jadra.Worker:latest"
    build:
      context: .
      dockerfile: ProjectManagement.Worker/Dockerfile
    depends_on:
      - redis
    networks:
      - normandy
      
  aws_ecr.api:
    image:  ${ECR_REGISTRY}/${ECR_REPOSITORY}:jadra.api:latest
    build:
      context: .
      dockerfile: ProjectManagement.API/Dockerfile
    depends_on:
      - redis
    networks:
      - normandy

  aws_ecr.worker:
    image: ${ECR_REGISTRY}/jadra.worker:latest
    build:
      context: .
      dockerfile: ProjectManagement.Worker/Dockerfile
    depends_on:
      - redis
    networks:
      - normandy

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=password123
    restart: always
    ports:
      - '7777:6379'
    networks:
      - normandy

networks:
  normandy:
    driver: bridge
