version: "3.4"

services:
  TASKMANAGEMENT_API:
    image: "${DOCKER_USERNAME}/jedra.api:latest"
    build:
      context: .
      dockerfile: ProjectManagement.API/Dockerfile
    depends_on:
      - redis
    networks:
      - normandy

  TASKMANAGEMENT_WORKER:
    image: "${DOCKER_USERNAME}/jedra.worker:latest"
    build:
      context: .
      dockerfile: ProjectManagement.Worker/Dockerfile
    depends_on:
      - redis
    networks:
      - normandy

networks:
  normandy:
    driver: bridge
