version: '3.4'

services:
  docker_api:
    image: ${{secret.DOCKER_USERNAME}}/Jadra.Api:latest
    build:
      context: .
      dockerfile: ProjectManagement.API/Dockerfile
    depends_on:
      - redis
    networks:
      - normandy

  projectmanagement_worker:
    image: ${{secret.DOCKER_USERNAME}}/Jadra.Worker:latest
    build:
      context: .
      dockerfile: ProjectManagement.Worker/Dockerfile
    depends_on:
      - redis
    networks:
      - normandy
      
  aws_ecr_api:
    image:  ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_WEBAPP}}-${{env.IMAGE_TAG}} .
    build:
      context: .
      dockerfile: ProjectManagement.API/Dockerfile
    depends_on:
      - redis
    networks:
      - normandy

  aws_ecr_worker:
    image: ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_WORKER}}-${{env.IMAGE_TAG}} .
    build:
      context: .
      dockerfile: ProjectManagement.Worker/Dockerfile
    depends_on:
      - redis
    networks:
      - normandy

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=password123
    restart: always
    ports:
      - '7777:6379'
    networks:
      - normandy

networks:
  normandy:
    driver: bridge
