version: "3.4"

services:
  ECR_API:
    image: "${ECR_REGISTRY}/${ECR_REPOSITORY_API}:${IMAGE_TAG}"
    build:
      context: .
      dockerfile: ProjectManagement.API/Dockerfile
    networks:
      - task_managment
  
  ECR_WORKER:
    image: "${ECR_REGISTRY}/${ECR_REPOSITORY_WORKER}:${IMAGE_TAG}"
    build:
      context: .
      dockerfile: ProjectManagement.Worker/Dockerfile
    networks:
      - task_managment

networks:
  task_managment:
    driver: bridge
