name: Docker Build and Push

on:
  push:
    branches:
      - master
env:
  IMAGE_WEBAPP: jadra.api
  IMAGE_WORKER: jadra.worker 
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and Push to DockerHub
      run: |
        docker-compose build
        docker-compose push TASKMANAGEMENT_API
        docker-compose push TASKMANAGEMENT_WORKER
