name: Docker Build and Push

on:
  push:
    branches:
      - master
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: jadra.api
  ECS_SERVICE: jadra_service
  ECS_CLUSTER: jadra_cluster
  ECS_TASK_DEFINITION: jadra-api-task-def
  IMAGE_WEBAPP: jadra.api
  IMAGE_WORKER: jadra.worker 
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build and Push to DockerHub & AWS ECR
      run: |
        docker-compose build
        docker-compose push docker.api
        docker-compose push projectmanagement.worker

        # Setting ECR image names
        export ECR_IMAGE_WEBAPP=$ECR_REGISTRY/$ECR_REPOSITORY:${{env.IMAGE_WEBAPP}}-$IMAGE_TAG
        export ECR_IMAGE_WORKER=$ECR_REGISTRY/$ECR_REPOSITORY:${{env.IMAGE_WORKER}}-$IMAGE_TAG

        # Tagging images for ECR
        docker tag $DOCKER_USERNAME/Jadra.Api:latest $ECR_IMAGE_WEBAPP
        docker tag $DOCKER_USERNAME/Jadra.Worker:latest $ECR_IMAGE_WORKER

        # Pushing to ECR
        docker push $ECR_IMAGE_WEBAPP
        docker push $ECR_IMAGE_WORKER
